### ISSUE TITLE
Cannot access files outside the sandbox

### ISSUE THREAD

**Issue by ptrv** [flathub/com.seventhstring.Transcribe#1]
I don't store my transcribe projects and audio files in the Music folder and cannot access them with the current sandbox permissions. Would it be possible to extend the filesystem permissions to host or home directory?

**Comment by MichaHoffmann** [comment]
Hey @ptrv 

would it be possible for you to launch the application with something like `flatpak run --filesystem=/path/to/transcriptions com.seventhstring.Transcribe`? I selected `xdg-music` only as a "sane default", so that the application cannot access anything in home by default and usually tweak those using flatseal in my installations.

Does this solve your issue?

**Comment by ptrv** [comment]
Hi @MichaHoffmann 

Yes, both of your suggestions solve the issue. Thanks for that.
However, IMHO it would be more convenient if it would work out of the box without having to tweak the exec command or using flatseal. But I can also understand if you want to keep the limited access as default.

**Comment by MichaHoffmann** [comment]
Hey @ptrv 

First of all, good that your issue is solved! I agree with your point about convenience, and eventually we could probably soften the access restrictions if its too cumbersome, but for now i would like to try and keep it as is!

Can we close this issue?

**Comment by ptrv** [comment]
Yes, closing.

**Comment by hfiguiere** [comment]
> First of all, good that your issue is solved! I agree with your point about convenience, and eventually we could probably soften the access restrictions if its too cumbersome, but for now i would like to try and keep it as is!

Given nobody can audit the code, that basically defeat the idea of sandboxing to "loosen" permissions to $HOME.
